kind: IngressController
apiVersion: operator.openshift.io/v1
metadata:
  name: test
  namespace: openshift-ingress-operator
spec:
  defaultCertificate:
    name: router-certs-default
  domain: router-test.example.com
  replicas: 1
  endpointPublishingStrategy:
    type: HostNetwork
  nodePlacement:
    nodeSelector:
      matchLabels:
        beta.kubernetes.io/os: linux
    tolerations:
    - effect: NoSchedule
      operator: Exists
  tlsSecurityProfile:
    type: Intermediate
