apiVersion: v1
data:
  secure-forward.conf: |
    <store>
      @type forward
      <server>
        host 192.168.1.2
        port 24220
      </server>
      <security>
        self_hostname $HOSTNAME
        shared_key oo_share_key
      </security>
    </store>
